# Generated by Django 5.2.14 on 2026-05-27 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('vocabulary', '0003_word_ease_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='next_review_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('student', 'word')},
        ),
    ]
