# Generated by Django 5.2.14 on 2026-05-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_alter_word_next_review_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='accepted_answers',
            field=models.JSONField(blank=True, default=list, help_text='List of alternative answers accepted as correct during review, in addition to the main word.'),
        ),
    ]
