# Generated by Django 5.2.14 on 2026-05-27 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quiz',
            name='unique_student_week',
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('student', 'week_start_date')},
        ),
    ]
