# Generated by Django 5.2.14 on 2026-05-27 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        # Drop the constraint referencing `student` before the field is
        # removed; SQLite remakes the table on field removal and would
        # otherwise fail recreating it with a constraint on a missing field.
        migrations.RemoveConstraint(
            model_name='score',
            name='unique_student_date',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='student',
        ),
        migrations.RemoveField(
            model_name='score',
            name='student',
        ),
        migrations.RemoveField(
            model_name='word',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='display_name',
        ),
        migrations.DeleteModel(
            name='GrammarCorrection',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
